### PR TITLE
Fix the paginator

### PR DESCRIPTION
**Pull request by philwareham**

### CODE REVIEW

**Comment by yauh** [comment]
Are you done from your end? If so I will do some testing and wrap it up as a 1.1 release :-)

**Comment by philwareham** [comment]
Yep. I'm done. You can test and go to v1.1 release (unless you find any bugs).

At some point I will see if a nice search field can be done using an idea like what's demoed here: http://spyrestudios.com/demos/sliding-panel-fixed/

Phil

On 4 Feb 2013, at 12:15, Stephan Hochhaus notifications@github.com wrote:

> Are you done from your end? If so I will do some testing and wrap it up as a 1.1 release :-)
> 
> —
> Reply to this email directly or view it on GitHub.

design hive limited
the old bakery
122 upper hale road
upper hale
farnham
surrey gu9 0jh
united kingdom
T 01252 734144
F 01252 734143
http://www.designhive.com/
registered in England and Wales no. 4566184
registered office: the old bakery, 122 upper hale road, upper hale, farnham, surrey gu9 0jh

**Comment by yauh** [comment]
Interesting slider, I like it - though going less minimal in style ;-)
I'll let you know if anything nasty pops up.
Thanks!

**Comment by yauh** [comment]
I added the slider - however without any search functionality yet. Maybe sometime later or if anyone wants to volunteer.

**Pull request merged**
