### PR TITLE
Couple of amends

### PR DESCRIPTION
**Pull request by philwareham**

### CODE REVIEW

**Comment by yauh** [comment]
thanks again :) 
I'll probably also add some slimbox functionality at some point - did so for yauh.de already.

**Comment by philwareham** [comment]
There seems to be a problem with the overlay on your slimbox, covers the image (tested in Firefox and Safari with same issue)

**Comment by philwareham** [comment]
To be honest, I wouldn't bother with the slimbox in the Minimum theme. Lightboxes are notoriously rubbish on small screen devices.

**Comment by yauh** [comment]
Thanks for the pointer to the slimbox issue. I stay mostly with Chrome these days and it was ok. Well, afterall slimbox won't make it in probably as the installation process gets a little more complex due to the js file. Or I need to find a cdn or misuse the styles functionality, which I would not like to do. Perhaps Minimum should stay small :)

**Comment by philwareham** [comment]
Agreed, keep it small and simple.

**Pull request closed without merging**
